generic/urls.py
from generic.views import *
from django.urls import path
app_name='generic'
urlpatterns=[
    path('vegetables/',vegetables,name='vegetables'),
]

project14/urls.py
from django.contrib import admin
from django.urls import path,include
from generic.views import *

import specific
urlpatterns = [
    path('admin/', admin.site.urls),
    path('vegetables/',vegetables,name='vegetables'),
    
    path('specific/',include('specific.urls')),
]

specific/urls.py
from specific.views import *
from django.urls import path
app_name='specific'
urlpatterns=[
    path('fruits/',fruits,name='fruits'),
    path('flowers/',flowers,name='flowers'),
]

generic/models.py
from django.db import models

# Create your models here.

specific/models.py
from django.db import models

# Create your models here.

generic/views.py
from django.shortcuts import render

# Create your views here.
def vegetables(request):
    return render(request,'vegetables.html')

specific/views.py
from django.shortcuts import render

# Create your views here.
def fruits(request):
    return render(request,'fruits.html')


def flowers(request):
    return render(request,'flowers.html')

templates/flowers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>FLOWERS</h1>
        <h1>There are so many beautiful flowers are there some of them are :</h1>
        <h1>1.Jamisine</h1>
        <h1>2.Rose</h1>
        <h1>etc..........</h1>
        <a href="{% url 'vegetables' %}">vegetables</a>
        <a href="{% url 'specific:fruits' %}">fruits</a>
    </center>
</body>
</html>

templates/fruits.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>FRUITS</h1>
        <h1>There are so many types of fruits</h1>
        <a href="{% url 'specific:flowers' %}">flower</a>
        <a href="{% url 'vegetables' %}">vegetables</a>
    </center>
</body>
</html>

templates/vegetables.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>VEGETABLES</h1>
        <h1>There are so many types of vegetables are there. Some are:</h1>
        <h1>1.Carrot</h1>
        <h1>2.tomato</h1>
        <h1>etc..........</h1>
        <a href="{% url 'specific:flowers' %}">flower</a>
        <a href="{% url 'specific:fruits' %}">fruits</a>
    </center>
</body>
</html>